{
 "title": "Demo",
 "time": { "from": "now-30s", "to": "now" },
 "refresh": "1s",
 "panels": [
  {
   "title": "Client A",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "http_success_response_client0_throughput{instance=\"localhost:8081\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "http_timeout_response_client0_throughput{instance=\"localhost:8081\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg_over_time(http_success_response_client0_throughput{instance=\"localhost:8081\"}[15s])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Client B",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "http_success_response_client0_throughput{instance=\"localhost:8082\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "http_timeout_response_client0_throughput{instance=\"localhost:8082\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg_over_time(http_success_response_client0_throughput{instance=\"localhost:8082\"}[15s])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Origin Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "http_request_origin_throughput", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Origin Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expr": "http_request_origin_latency", "legendFormat": "__auto" }
   ]
  }
 ]
}