global:
  scrape_interval: 2s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: server
    static_configs:
      - targets: ["localhost:8080"]
  - job_name: client
    static_configs:
      - targets: [ "localhost:8081" ]